# design a chrismas tree
print("           /*\              ")
print("          /***\               ")
print("         /*****\             ")
print("        /*******\           ")
print("       /*********\            ")
print("      /***********\           ")
print("     /*************\          ")
print("    /***************\          ")
print("   /_________________\          ")
print("           |||                  ")
print("           |||                  ")
print("           |||                  ")
print("           |||                  ")
print("           |||                  ")
print("           |||                  ")
print("           |||                  ")
