#  Design a logo
print ("_____________________________________________")
print ("|                                            |")
print ("|                                            |")
print ("|                                            |")
print ("|                  BARAKA                    |")
print ("|                  MUKIZA                    |")
print ("|                  KINYUA                    |")
print ("|           BORN-March 15th,2005             |")
print ("| Email address:barakakinyua2@gmail.com      |")
print ("|        Phone number:0740359342             |")
print ("|             Place:Mirema                   |")
print ("|                                            |")
print ("|                                            |")
print ("|                                            |")
print ("|                                            |")
print ("|                                            |")
print ("_____________________________________________")